# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

site_url: https://www.debordcounseling.com/
display_url: https://www.debordcounseling.com/

logo_url: https://www.debordcounseling.com/assets/img/uploads/debord-counseling-1-.png

# publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    preview_path: "{{filename}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  # CONFIG
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: URL, name: url, widget: string}
